name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Generate Static Site
        run: npx nuxi generate

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output/public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4